# ---------------------------------------
EMPRESA_NOMBRE_LARGO: Alimentos Vida S.A.
EMPRESA_DIRECCION_COMPLETA: Antonio Salellas 1825 - Parana - Entre Rios
EMPRESA_TELEFONOS:(0343) 4269400/4269444
EMPRESA_MAIL: vidalac@vidalac.com
EMPRESA_CUIT_CON_TITULO: CUIT: 30-71067391-4
EMPRESA_ING_BRUTOS_CON_TITULO: ING. BRUTOS Nᴼ: 908-619964-5
EMPRESA_INICIO_ACTIVIDAD_CON_TITULO: INICIO ACTIVIDADES: 12-08-2008
EMPRESA_COND_IVA_CON_TITULO: IVA RESP. INSCRIPTO 
EMPRESA_LOGO_200: AlimentosVidaLogo200.png

ACTIVIDAD_DETALLE_CORTO: Fabricación y Ventas de Productos Alimenticios

SERVER_IP: 127.0.0.1
BASE_DE_DATOS: vidalac
